// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/mapreduce.proto

package mapreduce

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MapReduceService_Map_FullMethodName    = "/mapreduce.MapReduceService/Map"
	MapReduceService_Reduce_FullMethodName = "/mapreduce.MapReduceService/Reduce"
	MapReduceService_Update_FullMethodName = "/mapreduce.MapReduceService/Update"
)

// MapReduceServiceClient is the client API for MapReduceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MapReduceServiceClient interface {
	// Mapper function
	Map(ctx context.Context, in *MapRequest, opts ...grpc.CallOption) (*MapResponse, error)
	// Reducer function
	Reduce(ctx context.Context, in *ReduceRequest, opts ...grpc.CallOption) (*ReduceResponse, error)
	// Work update function
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type mapReduceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMapReduceServiceClient(cc grpc.ClientConnInterface) MapReduceServiceClient {
	return &mapReduceServiceClient{cc}
}

func (c *mapReduceServiceClient) Map(ctx context.Context, in *MapRequest, opts ...grpc.CallOption) (*MapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapResponse)
	err := c.cc.Invoke(ctx, MapReduceService_Map_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapReduceServiceClient) Reduce(ctx context.Context, in *ReduceRequest, opts ...grpc.CallOption) (*ReduceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReduceResponse)
	err := c.cc.Invoke(ctx, MapReduceService_Reduce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapReduceServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, MapReduceService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapReduceServiceServer is the server API for MapReduceService service.
// All implementations must embed UnimplementedMapReduceServiceServer
// for forward compatibility.
type MapReduceServiceServer interface {
	// Mapper function
	Map(context.Context, *MapRequest) (*MapResponse, error)
	// Reducer function
	Reduce(context.Context, *ReduceRequest) (*ReduceResponse, error)
	// Work update function
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	mustEmbedUnimplementedMapReduceServiceServer()
}

// UnimplementedMapReduceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMapReduceServiceServer struct{}

func (UnimplementedMapReduceServiceServer) Map(context.Context, *MapRequest) (*MapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Map not implemented")
}
func (UnimplementedMapReduceServiceServer) Reduce(context.Context, *ReduceRequest) (*ReduceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reduce not implemented")
}
func (UnimplementedMapReduceServiceServer) Update(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedMapReduceServiceServer) mustEmbedUnimplementedMapReduceServiceServer() {}
func (UnimplementedMapReduceServiceServer) testEmbeddedByValue()                          {}

// UnsafeMapReduceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MapReduceServiceServer will
// result in compilation errors.
type UnsafeMapReduceServiceServer interface {
	mustEmbedUnimplementedMapReduceServiceServer()
}

func RegisterMapReduceServiceServer(s grpc.ServiceRegistrar, srv MapReduceServiceServer) {
	// If the following call pancis, it indicates UnimplementedMapReduceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MapReduceService_ServiceDesc, srv)
}

func _MapReduceService_Map_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapReduceServiceServer).Map(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapReduceService_Map_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapReduceServiceServer).Map(ctx, req.(*MapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapReduceService_Reduce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReduceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapReduceServiceServer).Reduce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapReduceService_Reduce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapReduceServiceServer).Reduce(ctx, req.(*ReduceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapReduceService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapReduceServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapReduceService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapReduceServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MapReduceService_ServiceDesc is the grpc.ServiceDesc for MapReduceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MapReduceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mapreduce.MapReduceService",
	HandlerType: (*MapReduceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Map",
			Handler:    _MapReduceService_Map_Handler,
		},
		{
			MethodName: "Reduce",
			Handler:    _MapReduceService_Reduce_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _MapReduceService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mapreduce.proto",
}
